// cookies for cookie module
cookie = [
"Chocolate Chip",
"Oatmeal", 
"Sugar", 
"Oatmeal Raisin", 
"Macadamia Nut", 
"Jam Thumbprint", 
"Biscotti", 
"Oatmeal Cranberry", 
"Chocolate Fudge", 
"Peanut Butter", 
"Pumpkin",  
"Chocolate Oatmeal Fudge", 
"Toffee Peanut", 
"Danish Sugar", 
"Triple Chocolate", 
"Half-Moon", 
"Butter Pecan",
"Coconut Macaroon", 
"Custard Cream", 
"Digestive Biscuit", 
"Fig Roll", 
"Empire Biscuit", 
"Fortune", 
"Fudge", 
"Macaroon", 
"Maple Leaf Cream", 
"Marie Biscuit", 
"Oreo", 
"Rainbow", 
"Shortbread", 
];
